// Generated by https://quicktype.io

export interface F007 {
  success: string;
  result:  Result;
  records: Records;
}

export interface Records {
  Locations: RecordsLocation[];
}

export interface RecordsLocation {
  DatasetDescription: string;
  LocationsName:      string;
  Dataid:             string;
  Location:           LocationLocation[];
}

export interface LocationLocation {
  LocationName:   string;
  Geocode:        string;
  Latitude:       string;
  Longitude:      string;
  WeatherElement: WeatherElement[];
}

export interface WeatherElement {
  ElementName: any;
  Time:        Time[];
}

export interface Time {
  DataTime?:    Date;
  ElementValue: ElementValue[];
  StartTime?:   Date;
  EndTime?:     Date;
}

export interface ElementValue {
  Temperature?:                string;
  DewPoint?:                   string;
  RelativeHumidity?:           string;
  ApparentTemperature?:        string;
  ComfortIndex?:               string;
  ComfortIndexDescription?:    string;
  WindSpeed?:                  string;
  BeaufortScale?:              string;
  WindDirection?:              string;
  ProbabilityOfPrecipitation?: string;
  Weather?:                    string;
  WeatherCode?:                string;
  WeatherDescription?:         string;
}

export interface Result {
  resource_id: string;
  fields:      Field[];
}

export interface Field {
  id:   string;
  type: Type;
}

export enum Type {
  String = "String",
  Timestamp = "Timestamp",
}
